name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./sentinal_backend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Maven Build and Tests
        run: ./mvnw clean verify
